# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Ant build release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # triggers the workflow every day at 5:30 and 17:30 UTC:
    - cron:  '30 5,17 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
      
    - name: Upload the artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: dist

    - name: Rename the artifacts
      run: mv dist eewd

    - name: Zip the artifacts
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r eewd.zip eewd
    
    - name: Release the zip
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: eewd.zip
